---
title: "R체ckmeldungen zu den Wahlen im Kanton Z체rich 2019"
output:
  html_document:
    df_print: paged
---

Zusammenfassung zu den R체ckmeldungen zum Webauftritt und dem Datenservice w채hrend der Regierungsrats- und Kantonsratswahlen 2019.

```{r, include = FALSE, echo=FALSE, warning=FALSE}
#Setup
library(egg)

library(tidyverse)
library(ggplot2)
library(openxlsx)
library(stringr)

```

```{r, include = FALSE, echo=FALSE, warning=FALSE}

#Import Data

BesucherNachZeit <- read.csv("data/besucher.csv", sep=",", header= TRUE, fill=TRUE)



downloads <- read.csv("data/downloads_20190324.csv", sep=",", header= TRUE, fill=TRUE, stringsAsFactors =FALSE)

downloads_top <- downloads %>% 
                  top_n(10, Downloads) %>% 
                  mutate(Bezeichnung = str_replace(Bezeichnung, "www.wahlen.zh.ch/wahlen2019/public/","")) %>%
                  mutate(Bezeichnung = str_replace(Bezeichnung, "www.wahlen.zh.ch/wahlen2019/intern/","")) %>%  
                  mutate(Bezeichnung = str_replace(Bezeichnung, "www.wahlen.zh.ch/wahlen2019/medien/","")) %>%
                  mutate(Bezeichnung = str_replace(Bezeichnung, "www.wahlen.zh.ch/krdaten_staatsarchiv/","")) %>% 
                  select(Bezeichnung, Downloads, Eindeutige.Downloads) %>% 
                  gather("key", "Anzahl", -Bezeichnung) %>% 
                  mutate(key = factor(key, levels = c("Eindeutige.Downloads" ,"Downloads" ))) 





BesucherNachZeit_bearbeitet <- BesucherNachZeit %>% 
                                select(Uhrzeit = Bezeichnung, Eindeutige.Besucher) %>% 
                                gather("key","Anzahl", -Uhrzeit)


aktionen <- BesucherNachZeit %>% 
                                select(Uhrzeit = Bezeichnung, Aktionen) %>% 
                                gather("key","Anzahl", -Uhrzeit)

Bewertung <- read.xlsx("data/rating.xlsx")




stars <- c(paste(sprintf('\u2605')), paste(sprintf('\u2605'), sprintf('\u2605')),  paste(sprintf('\u2605'), sprintf('\u2605'), sprintf('\u2605')), paste(sprintf('\u2605'), sprintf('\u2605'), sprintf('\u2605'), sprintf('\u2605')), paste(sprintf('\u2605'), sprintf('\u2605'), sprintf('\u2605'), sprintf('\u2605') , sprintf('\u2605')) )

Bewertung <- Bewertung %>% mutate(stars = stars)

```

# Anzahl Besucher pro Stunde
```{r, echo=  FALSE,  warning=FALSE, fig.align="left"}

#plot the Visitor Data

p_visitor <- ggplot(data=BesucherNachZeit_bearbeitet, aes(x=Uhrzeit, y=Anzahl, fill=key)) +
                geom_bar(stat="identity", position=position_dodge()) + 
                theme(axis.text.x = element_text( angle=90, vjust = 0.3)) +
                guides(fill=guide_legend(title="Typ")) + scale_y_continuous(labels=scales::comma_format(big.mark = "'"))

grid.arrange(grobs = lapply(
list(p_visitor),
set_panel_size,
width = unit(10, "cm"),
height = unit(10, "cm")
)) 
```

* [Daten Besucher nach Zeit](data/besucher.csv) - csv

# Aktionen pro Stunde
```{r, echo=  FALSE,  warning=FALSE, fig.align="left"}

#plot the Visitor Data

p_visitor <- ggplot(data=aktionen, aes(x=Uhrzeit, y=Anzahl, fill=key)) +
                geom_bar(stat="identity", position=position_dodge()) + 
                theme(axis.text.x = element_text( angle=90, vjust = 0.3)) +
                guides(fill=guide_legend(title="Typ"))  +
                theme(plot.margin=unit(c(0,0,0,6), "cm")) + 
  scale_y_continuous(labels=scales::comma_format(big.mark = "'"))


 grid.arrange( grobs = lapply(
 list(p_visitor),
 set_panel_size,
 width = unit(10, "cm"),
 height = unit(10, "cm")
 ), ncol=2) 

```


# Datendownload

```{r, echo=  FALSE,  warning=FALSE, fig.width=8.5}


download_plot <- ggplot(data=downloads_top, aes(x=reorder(Bezeichnung,Anzahl), y=Anzahl, fill =key)) +
          geom_bar(stat="identity", position=position_dodge()) + 
          coord_flip() + 
          labs(x="") + 
          guides(fill=guide_legend(title="Typ")) +
          theme(axis.text=element_text(size=9),
                axis.title=element_text(size=9),
                plot.margin=unit(c(0,0,0,0), "cm")) + scale_y_continuous(labels=scales::comma_format(big.mark = "'"))



 grid.arrange( grobs = lapply(
 list(download_plot),
 set_panel_size,
 width = unit(10, "cm"),
 height = unit(10, "cm")
 )) 
```




# Bewertung der Seite
```{r, echo = FALSE,  warning=FALSE, fig.align="left"}
#plot the rating

p_rating <- ggplot(data=Bewertung, aes(x=stars, y=Anzahl.Bewertungen)) +
                geom_bar(stat="identity", fill="steelblue")  + 
                coord_flip() +  
                labs(y= "Anzahl Bewertungen", x = "Anzahl Sterne") +
                theme(plot.margin=unit(c(0,0,0,4), "cm")) 

 grid.arrange( grobs = lapply(
 list(p_rating),
 set_panel_size,
 width = unit(10, "cm"),
 height = unit(10, "cm")
 ), ncol=2) 


#ggarrange(p_rating,debug = TRUE)


#ggarrange(p_visitor,p_rating,debug = TRUE)
```

